
=head1 NAME

WebService::Pinterest - Pinterest API client

=head1 SYNOPSIS


    use WebService::Pinterest;

    $pinterest = WebService::Pinterest->new( access_token => $access_token );

    $r1 = $pinterest->fetch('me/pins');
    $r2 = $pinterest->fetch( '/user/pins', user => $user_id );

    $r3 = $pinterest->create( 'me/board', board => 'nobody/board' );
    $r4 = $pinterest->create(
        'me/pin',
        board     => 'nobody/board',
        note      => '',
        image_url => '',
        link      => '',
    );

    $r5 = $pinterest->edit( 'me/pin', pin => 9999999, note => 'xxx', link => 'http://' );

    $pinterest = WebService::Pinterest->new(
        app_id     => $client_id,
        app_secret => $secret
    );
    $url = $pinterest->authorization_url(
        response_type => 'code',
        state         => $state,
        scope         => 'read_public',
        redirect_uri  => 'https://my.app.com/connect/pinterest',
    );

    $res = $pinterest->get_access_token(
        grant_type => 'authorization_code',
        code       => $code,
    );

=head2 PAGINATION

See https://developers.pinterest.com/docs/api/overview/#pagination


    $it = $api->paged_fetch('board/pins', board => $board, limit => 50);
    while ($res = $it->next) {
        ...
    }

